services:
    - type: web
      name: skribble-server
      env: node
      plan: free
      rootDir: server
      buildCommand: pnpm install && pnpm exec prisma generate && pnpm exec prisma migrate deploy && pnpm run build
      startCommand: pnpm run start
      healthCheckPath: /health
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            sync: false
          - key: METRICS_TOKEN
            generateValue: true
